### ISSUE TITLE
The `--data-raw` attribute is not working

### ISSUE THREAD

**Issue by noviluni** [michael-shub/curl2scrapy#5]
The support could be added by modifying the regex here to incorporate `--data-raw` as a synonym of --data`:

`let postRegex = /\s(--data|--data-binary) \S/`

**Comment by michael-shub** [comment]
Thanks for the notice, will fix asap (:

**Comment by michael-shub** [comment]
> The support could be added by modifying the regex here to incorporate `--data-raw` as a synonym of --data`:
> 
> `let postRegex = /\s(--data|--data-binary) \S/`

Fixed (: Let me know if there are anymore errors/requests
