### ISSUE TITLE
compatibility with postman curl export

### ISSUE THREAD

**Issue by revalenza** [michael-shub/curl2scrapy#6]
hi, the page doesn't seem to work with the curl string generate by Postman

![image](https://user-images.githubusercontent.com/44981950/88938364-4d58b880-d253-11ea-83df-0b09d6262553.png)

i try changing the config making it export the string in only one line and use the short name of options, the page seems to think that location option is the url and ingore everything else i add

![image](https://user-images.githubusercontent.com/44981950/88938636-93ae1780-d253-11ea-9fe7-c19a31adc957.png)

![image](https://user-images.githubusercontent.com/44981950/88938823-c9eb9700-d253-11ea-82e8-ddb0a6aaedd0.png)

thanks!

**Comment by michael-shub** [comment]
Thanks, @revalenza  Reworking is in progress already (: 
Can you please attach text version of curl command from postman, since I don't have one.

**Comment by revalenza** [comment]
Short
`curl -L -X POST 'https://postman-echo.com/post' -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'strange=boom'`
Long
`curl --location --request POST 'https://postman-echo.com/post' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'strange=boom'`
Long with line continuation character (default option, see first image)
`curl --location --request POST 'https://postman-echo.com/post' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'strange=boom'`

**Comment by michael-shub** [comment]
> Short
> `curl -L -X POST 'https://postman-echo.com/post' -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'strange=boom'`
> Long
> `curl --location --request POST 'https://postman-echo.com/post' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'strange=boom'`
> Long with line continuation character (default option, see first image)
> `curl --location --request POST 'https://postman-echo.com/post' \ --header 'Content-Type: application/x-www-form-urlencoded' \ --data-urlencode 'strange=boom'`

Thank you! It's been a while, but I've improved parsing of different format of curl command. It seems like now it works. Feel free to take a look and leave any feedback.
Kind regards (:
